import type { Metadata } from "next";
import "./globals.css";
import { register } from "../instrumentation";
import Header from "./header";
import styles from "./layout.module.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

register();

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={styles.main}>
        <Header />
        <main>{children}</main>
      </body>
    </html>
  );
}
